### ISSUE TITLE
Client price?

### ISSUE THREAD

**Issue by xied75** [docker/dockercraft#16] opened 2015-11-18 14:44 UTC
Per the GitHub spirit, everything we raise as an issue:

The Client is just too much $$$

If I only intend to use the client to manage my docker containers, shouldn't I be able to download a "Community" version for free? Besides given its use, I now declare Minecraft should under the Devs division on par with Visual Studio so that eventually we get VSCraft.

Edit: Anyone interested donate a copy to me I'll extend/modify features you want. :)

**Comment by Chnkr** [comment] 2015-11-19 05:11
DockerCraft does not maintain minecraft.

**Comment by ghostsquad** [comment] 2015-11-19 05:57
Minecraft is well worth the relatively low price of $26.95 US. Whether you use it for this purpose or for the purpose it was intended.

**Comment by xied75** [comment] 2015-11-19 09:30
@Chnkr yes that's common sense.

@ghostsquad it's 17.95 £ in the UK. But you need to change your angle to people who is NOT into Minecraft before who in the first time of their life saw the light is coming. Or is it general rule all Devs/DevOps by default should have MineCraft on their PC?

**Comment by ghostsquad** [comment] 2015-11-19 16:19
Lol... I dunno. I love Minecraft. I found out that about a dozen people at
work like it too. We play Minecraft daily. ☺

**Comment by xied75** [comment] 2015-11-19 16:26
@ghostsquad That's exactly what I guessed, that you guys play MC all day long and code a bit for break.

Now we need a channel to ask Microsoft to give us free licenses for dockercraft development...

**Comment by joranbeasley** [comment] 2015-11-19 16:46
Im pretty sure microsoft doesnt have anything to do with minecraft either ...

**Comment by ghostsquad** [comment] 2015-11-19 18:03
@xied75 lol - not quite.
@joranbeasley - google search "Microsoft Buys Minecraft for $2.5 billion"

**Comment by dave-tucker** [comment] 2015-12-04 15:10
Closing this issue as the Minecraft client is outside of our control

**Closed by dave-tucker** 2015-12-04 15:10 UTC
